version: "3.8"

services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"

  wanderlust:
    container_name: wanderlust
    build: .
    env_file:
      - ./backend/.env.sample
      - ./frontend/.env.sample
    ports:
      - "8080:8080"
      - "5173:5173"
    depends_on:
      - mongodb

volumes:
  data:
